name: Bug Report
description: Report a problem with the data, site, or scripts
title: "[BUG] "
labels: [bug]
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Describe how to reproduce the issue step by step.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?

  - type: textarea
    attributes:
      label: Actual Behavior
      description: What actually happened?

  - type: input
    attributes:
      label: Relevant Page or File
      description: |
        If applicable, paste the URL or path (e.g. `/public/data/stock/XXXX.json` or `/src/pages/StockPage.tsx`)
    validations:
      required: false
